package ship.f.engine.shared.core

import kotlinx.serialization.Serializable

@Serializable
abstract class ScopedEvent {
    @Serializable
    data class InitialEvent(val name: String) : ScopedEvent() { //I may be making an error with this scope implementation as well... Actually, I might be okay
        override fun getScopes(): List<ScopeTo> = listOf(ScopeTo.SingleScopeTo(value = name))
    }

    abstract fun getScopes(): List<ScopeTo> // will be generated by KSP
}

@Serializable
abstract class Event : ScopedEvent() {
    override fun getScopes(): List<ScopeTo> = emptyList()
}